// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/walproto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalRecord struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Data              []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	LogSequenceNumber uint64                 `protobuf:"varint,1,opt,name=LogSequenceNumber,proto3" json:"LogSequenceNumber,omitempty"`
	Timestamp         int64                  `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Checksum          uint32                 `protobuf:"varint,4,opt,name=Checksum,proto3" json:"Checksum,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_proto_walproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_walproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_proto_walproto_proto_rawDescGZIP(), []int{0}
}

func (x *WalRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WalRecord) GetLogSequenceNumber() uint64 {
	if x != nil {
		return x.LogSequenceNumber
	}
	return 0
}

func (x *WalRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WalRecord) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

var File_proto_walproto_proto protoreflect.FileDescriptor

const file_proto_walproto_proto_rawDesc = "" +
	"\n" +
	"\x14proto/walproto.proto\"\x87\x01\n" +
	"\tWalRecord\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12,\n" +
	"\x11LogSequenceNumber\x18\x01 \x01(\x04R\x11LogSequenceNumber\x12\x1c\n" +
	"\tTimestamp\x18\x02 \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bChecksum\x18\x04 \x01(\rR\bChecksumB\x10Z\x0ewalproto/protob\x06proto3"

var (
	file_proto_walproto_proto_rawDescOnce sync.Once
	file_proto_walproto_proto_rawDescData []byte
)

func file_proto_walproto_proto_rawDescGZIP() []byte {
	file_proto_walproto_proto_rawDescOnce.Do(func() {
		file_proto_walproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_walproto_proto_rawDesc), len(file_proto_walproto_proto_rawDesc)))
	})
	return file_proto_walproto_proto_rawDescData
}

var file_proto_walproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_walproto_proto_goTypes = []any{
	(*WalRecord)(nil), // 0: WalRecord
}
var file_proto_walproto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_walproto_proto_init() }
func file_proto_walproto_proto_init() {
	if File_proto_walproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_walproto_proto_rawDesc), len(file_proto_walproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_walproto_proto_goTypes,
		DependencyIndexes: file_proto_walproto_proto_depIdxs,
		MessageInfos:      file_proto_walproto_proto_msgTypes,
	}.Build()
	File_proto_walproto_proto = out.File
	file_proto_walproto_proto_goTypes = nil
	file_proto_walproto_proto_depIdxs = nil
}
